version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - PizzageddonDB:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
    - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

volumes:
  PizzageddonDB:
